export interface TimezoneOption {
  label: string
  value: string
}

export const timezones: TimezoneOption[] = [
  { label: "(UTC) Coordinated Universal Time", value: "UTC" },
  { label: "(UTC-12:00) International Date Line West", value: "UTC-12" },
  { label: "(UTC-11:00) Coordinated Universal Time-11", value: "UTC-11" },
  { label: "(UTC-10:00) Hawaii", value: "UTC-10" },
  { label: "(UTC-09:00) Alaska", value: "UTC-09" },
  { label: "(UTC-08:00) Baja California", value: "UTC-08" },
  { label: "(UTC-08:00) Pacific Standard Time (US & Canada)", value: "PST" },
  { label: "(UTC-07:00) Arizona", value: "UTC-07-AZ" },
  { label: "(UTC-07:00) Chihuahua, La Paz, Mazatlan", value: "UTC-07-MX" },
  { label: "(UTC-07:00) Mountain Time (US & Canada)", value: "MST" },
  { label: "(UTC-06:00) Central America", value: "UTC-06" },
  { label: "(UTC-06:00) Central Time (US & Canada)", value: "CST" },
  { label: "(UTC-06:00) Guadalajara, Mexico City, Monterrey", value: "UTC-06-MX" },
  { label: "(UTC-06:00) Saskatchewan", value: "UTC-06-CA" },
  { label: "(UTC-05:00) Bogota, Lima, Quito, Rio Branco", value: "UTC-05" },
  { label: "(UTC-05:00) Eastern Time (US & Canada)", value: "EST" },
  { label: "(UTC-05:00) Indiana (East)", value: "EST-IN" },
  { label: "(UTC-04:00) Atlantic Time (Canada)", value: "AST" },
  { label: "(UTC-04:00) Caracas, La Paz", value: "UTC-04" },
  { label: "(UTC-04:00) Manaus", value: "UTC-04-BR" },
  { label: "(UTC-04:00) Santiago", value: "UTC-04-CL" },
  { label: "(UTC-03:30) Newfoundland", value: "NST" },
  { label: "(UTC-03:00) Brasilia", value: "UTC-03-BR" },
  { label: "(UTC-03:00) Buenos Aires, Georgetown", value: "UTC-03-AR" },
  { label: "(UTC-03:00) Greenland", value: "UTC-03-GL" },
  { label: "(UTC-03:00) Montevideo", value: "UTC-03-UY" },
  { label: "(UTC-02:00) Mid-Atlantic", value: "UTC-02" },
  { label: "(UTC-01:00) Azores", value: "UTC-01-AZ" },
  { label: "(UTC-01:00) Cape Verde Is.", value: "UTC-01" },
  { label: "(UTC+00:00) Casablanca", value: "UTC+00" },
  { label: "(UTC+00:00) Dublin, Edinburgh, Lisbon, London", value: "GMT" },
  { label: "(UTC+00:00) Monrovia, Reykjavik", value: "UTC+00-IS" },
  { label: "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna", value: "CET" },
  { label: "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague", value: "CET-EE" },
  { label: "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris", value: "CET-WE" },
  { label: "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb", value: "CET-YU" },
  { label: "(UTC+01:00) West Central Africa", value: "WAT" },
  { label: "(UTC+02:00) Amman", value: "EET-JO" },
  { label: "(UTC+02:00) Athens, Bucharest, Istanbul", value: "EET" },
  { label: "(UTC+02:00) Beirut", value: "EET-LB" },
  { label: "(UTC+02:00) Cairo", value: "EET-EG" },
  { label: "(UTC+02:00) Harare, Pretoria", value: "CAT" },
  { label: "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius", value: "EET-FI" },
  { label: "(UTC+02:00) Jerusalem", value: "IST" },
  { label: "(UTC+02:00) Minsk", value: "MSK-M" },
  { label: "(UTC+02:00) Windhoek", value: "WAT-NA" },
  { label: "(UTC+03:00) Baghdad", value: "AST-IQ" },
  { label: "(UTC+03:00) Kuwait, Riyadh", value: "AST-SA" },
  { label: "(UTC+03:00) Moscow, St. Petersburg, Volgograd", value: "MSK" },
  { label: "(UTC+03:00) Nairobi", value: "EAT" },
  { label: "(UTC+03:30) Tehran", value: "IRST" },
  { label: "(UTC+04:00) Abu Dhabi, Muscat", value: "GST" },
  { label: "(UTC+04:00) Baku", value: "AZT" },
  { label: "(UTC+04:00) Port Louis", value: "MUT" },
  { label: "(UTC+04:00) Tbilisi", value: "GET" },
  { label: "(UTC+04:00) Yerevan", value: "AMT" },
  { label: "(UTC+04:30) Kabul", value: "AFT" },
  { label: "(UTC+05:00) Ekaterinburg", value: "YEKT" },
  { label: "(UTC+05:00) Islamabad, Karachi, Tashkent", value: "PKT" },
  { label: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi", value: "IST-IN" },
  { label: "(UTC+05:45) Kathmandu", value: "NPT" },
  { label: "(UTC+06:00) Almaty, Novosibirsk" , value: "ALMT" },
  { label: "(UTC+06:00) Astana, Dhaka", value: "BST" },
  { label: "(UTC+06:30) Yangon (Rangoon)", value: "MMT" },
  { label: "(UTC+07:00) Bangkok, Hanoi, Jakarta", value: "ICT" },
  { label: "(UTC+07:00) Krasnoyarsk", value: "KRAT" },
  { label: "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi", value: "CST-CN" },
  { label: "(UTC+08:00) Kuala Lumpur, Singapore", value: "SGT" },
  { label: "(UTC+08:00) Irkutsk", value: "IRKT" },
  { label: "(UTC+08:00) Perth", value: "AWST" },
  { label: "(UTC+08:00) Taipei", value: "NST-TW" },
  { label: "(UTC+08:00) Ulaanbaatar", value: "ULAT" },
  { label: "(UTC+09:00) Osaka, Sapporo, Tokyo", value: "JST" },
  { label: "(UTC+09:00) Seoul", value: "KST" },
  { label: "(UTC+09:00) Yakutsk", value: "YAKT" },
  { label: "(UTC+09:30) Adelaide", value: "ACDT" },
  { label: "(UTC+09:30) Darwin", value: "ACST" },
  { label: "(UTC+10:00) Brisbane", value: "AEST-QLD" },
  { label: "(UTC+10:00) Canberra, Melbourne, Sydney", value: "AEST" },
  { label: "(UTC+10:00) Hobart", value: "AEDT" },
  { label: "(UTC+10:00) Guam, Port Moresby", value: "ChST" },
  { label: "(UTC+10:00) Vladivostok", value: "VLAT" },
  { label: "(UTC+11:00) Magadan, Solomon Is., New Caledonia", value: "SRET" },
  { label: "(UTC+12:00) Auckland, Wellington", value: "NZDT" },
  { label: "(UTC+12:00) Fiji, Kamchatka, Marshall Is.", value: "FJT" },
  { label: "(UTC+13:00) Nuku'alofa", value: "TOT" }
]
